### ISSUE TITLE
Changed password: Deploying plugin doesn't work anymore

### ISSUE THREAD

**Issue by zaha** [jlattimer/D365DeveloperExtensions#21]
Hi,

yesterday I had to change my AD password. Today, when I tried to deploy a plugin to our D365 Azure Instance I received the following error:

```
Error creating or updating assembly: Type: MyPlugin.Assembly;

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Update(Entity entity)
   at PluginDeployer.Crm.Assembly.UpdateCrmAssembly(CrmServiceClient client, CrmAssembly crmAssembly)
```

Since I also had problems with the XrmToolBox when trying to connect to the CRM due to the password change, I assume this is the same here as it was working fine the days before. Is there any way how I can reset/change my user credentials PW?

Kind regards
Michael

**Comment by jlattimer** [comment]
What if you uncheck the auto login and then select No to reset credentials?

**Comment by zaha** [comment]
I was able to login with my new credentials, but the error persists unfortunately. Maybe it's not related to the PW change after all. 

Then I'm not sure what's wrong here. The setup was working 3 days ago and I can't think of anything that's changed since then (except for the plugin code, of course ;) ).

**Comment by jlattimer** [comment]
Can you log in with the plug-in registration tool from the SDK?

**Comment by zaha** [comment]
Yes, also with the Plugin Registration Tool from the XrmToolBox. With the latter I also successfully deployed.

**Comment by jlattimer** [comment]
I did release a new version (2.0.1876.321) which likely was installed in the background. Or if you don't have it, update. I did add a small piece to authentication to allow for MFA. I just tried changing my domain password - as expected I couldn't log in with my old password but could with the new one.

**Comment by zaha** [comment]
It was actually updated to the latest version in the background.

I just did another test: Deploying web resources works fine. I also tried to retrieve Plug-in Trace Logs and received the following error:

```
ERROR | 16.03.2018 08:10:57: Error retrieving plug-in trace logs: The date-time format for 15.03.2018 08:10:55 is invalid, or value is outside the supported range.

Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.RetrieveMultiple(QueryBase query)
   at PluginTraceViewer.Crm.PluginTrace.RetrievePluginTracesFromCrm(CrmServiceClient client, DateTime afterDate)
```

Not sure if this is related, though.

**Comment by jlattimer** [comment]
What version of CRM/D365 are you on?

**Comment by zaha** [comment]
We're currently on:

Microsoft Dynamics 365
Version 1612 (8.2.2.339) (DB 8.2.2.339) online

**Comment by jlattimer** [comment]
This error is something else - I'm guessing if you can log in now that the password issue was something temporary.

**Comment by thijskuipers** [comment]
Hi, just reading the error, I think the problem is here: https://github.com/jlattimer/D365DeveloperExtensions/blob/41c722702c7c3423cc5cb29cb41ab4992b9fb46b/PluginTraceViewer/Crm/PluginTrace.cs#L39
You depend on the default serialization of the DateTime, which is culture dependent. Hence the error `The date-time format for 15.03.2018 08:10:55 is invalid`. Choose e.g. the [Roundtrip "O"](https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-date-and-time-format-strings#the-round-trip-o-o-format-specifier) format.
