### ISSUE TITLE
PlugIn Deployer Crashing Visual Studio

### ISSUE THREAD

**Issue by jeevan264** [jlattimer/D365DeveloperExtensions#25]
Testing this on both VS 2015 and 2017, except Plugin Deployer rest works fine on VS 2015. everytime i try to publish from Plugin deployer, it crashes my VS 2015.

On my VS 2017, all the deployers crashing the VS.

Thanks
Jeevan

**Comment by jlattimer** [comment]
Can you confirm you are on the latest version 2.0.1888.0240 ?
Can you turn on logging under Tools > Options > D365DevEx > Logging > Enable detailed extension logging to see if it catches anything?
Is there anything special about the plug-in set up? Using base classes etc.?

**Comment by JeroenLeeflang** [comment]
I have the same problem. I have the latest version. I enabled the logging, but nothing is logged in the logfile, except that the extension is initializing.

Just a test assembly with one plugin.

**Comment by jlattimer** [comment]
1534 is the latest release.

**Comment by jlattimer** [comment]
Is someone able to get me an example of a plug-in causing the tool to crash? Or is this happening without a project loaded?

**Comment by FixRM** [comment]
@jlattimer This is a basic plugin:

public class SamplePlugin : IPlugin
    {
        #region Secure/Unsecure Configuration Setup
        private readonly string _secureConfig = null;
        private readonly string _unsecureConfig = null;

        public SamplePlugin(string unsecureConfig, string secureConfig)
        {
            _secureConfig = secureConfig;
            _unsecureConfig = unsecureConfig;
        }
        #endregion
        public void Execute(IServiceProvider serviceProvider)
        {
            ITracingService tracer = (ITracingService)serviceProvider.GetService(typeof(ITracingService));
            IPluginExecutionContext context = (IPluginExecutionContext)serviceProvider.GetService(typeof(IPluginExecutionContext));
            IOrganizationServiceFactory factory = (IOrganizationServiceFactory)serviceProvider.GetService(typeof(IOrganizationServiceFactory));
            IOrganizationService service = factory.CreateOrganizationService(context.UserId);

            try
            {
                //Entity entity = (Entity)context.InputParameters["Target"];

                //TODO: Do stuff
            }
            catch (Exception e)
            {
                throw new InvalidPluginExecutionException(e.Message);
            }
        }
    }

VS crash during registration. No matter which deployment type is used. But I found a workaround:

1. Add spkl via NuGet
2. Deploy once with spkl
3. Now plugin can be updated without crashes

**Comment by FixRM** [comment]
The only problem is I don't like spkl attribute based approach but spkl regex registration option seems too be broken as well, or I didn't get how too use it :)

**Comment by PederBennedsen** [comment]
Same problem here. Even after creating a new solution with only basic template, VS2017 still crashes.

**Comment by JanPadysak** [comment]
Hi, we have the same problem, we are using the latest version 2.0.18109.1534 of D365 extensnion and when we try to publish an assembly with a simple CodeActivity 

> public class TestCustomActivity: CodeActivity
{
        protected override void Execute(CodeActivityContext context)
        {
            var tracingService = context.GetExtension<ITracingService>();
            tracingService.Trace($"Custom step {nameof(TestCustomStep)} triggered.");
        }
    }

the VS will crash when we click "Publish" button in D365 plugin deployer.

Erro in event log:

> Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Linq.Enumerable.First[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at PluginDeployer.SpklHelpers.AssemblyProperties(System.String, Boolean)
   at PluginDeployer.PluginDeployerWindow+<PublishAssemblyAsync>d__32.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at PluginDeployer.PluginDeployerWindow+<Publish_OnClick>d__31.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
