### ISSUE TITLE
Web Resource Deployer crashing after connected to CRM

### ISSUE THREAD

**Issue by penzesl** [jlattimer/D365DeveloperExtensions#29]
It worked fine yesterday when I initially set up the VS project. Then I tried to connect to another D365 environment which contains the same web resources. Now I get this shortly after "Retrieving solutions and web resources" is displayed:

Exception Info: System.NullReferenceException
   at WebResourceDeployer.Config.Mapping.GetSpklConfigWebresourceFiles(System.String, D365DeveloperExtensions.Core.Models.SpklConfig)
   at WebResourceDeployer.Config.Mapping.HandleSpklMappings(EnvDTE.Project, System.String, System.Collections.ObjectModel.ObservableCollection`1<WebResourceDeployer.ViewModels.WebResourceItem>)
   at WebResourceDeployer.WebResourceDeployerWindow+<GetWebResources>d__76.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at WebResourceDeployer.WebResourceDeployerWindow+<GetCrmData>d__74.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at WebResourceDeployer.WebResourceDeployerWindow+<LoadData>d__38.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by ct-tnguyen** [comment]
I have the same issue. I had to delete my spkl.json to prevent the crashing. So I lost all my mappings.

**Comment by penzesl** [comment]
Deleting spkl.json unfortunately did not solve the problem for me.

Profile drop-down is empty, isn't it the cause of NullReferenceException?
![kep](https://user-images.githubusercontent.com/38991661/44573818-551ea100-a790-11e8-838a-c83bdb83289f.png)
