### ISSUE TITLE
VS 2017 crashing while connecting to Dynamics 365 

### ISSUE THREAD

**Issue by naveedmcp** [jlattimer/D365DeveloperExtensions#67]
Hi,
While connecting to Dynamics 365 from D365 DevEx Solution packager tool, VS crashing. I noticed that previously there was some value in profile when it was working fine but when the crash happen I can see that profile value was not there.

![image](https://user-images.githubusercontent.com/31393621/61147060-820f9b80-a4a9-11e9-8f96-116542208499.png)

Getting exception;

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at SolutionPackager.Config.Mapping.GetSolutionPackageConfig(EnvDTE.Project, System.String, System.Collections.ObjectModel.ObservableCollection`1<SolutionPackager.ViewModels.CrmSolution>)
   at SolutionPackager.SolutionPackagerWindow+<GetSolutions>d__35.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at SolutionPackager.SolutionPackagerWindow+<GetCrmData>d__34.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at SolutionPackager.SolutionPackagerWindow+<LoadData>d__22.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

----

Faulting application name: devenv.exe, version: 15.9.28307.280, time stamp: 0x5c2fb055
Faulting module name: KERNELBASE.dll, version: 10.0.17134.799, time stamp: 0x0117c7be
Exception code: 0xe0434352
Fault offset: 0x00112c92
Faulting process id: 0x7880
Faulting application start time: 0x01d538d65f1949d7
Faulting application path: XXXX\devenv.exe
Faulting module path: XXX\System32\KERNELBASE.dll
Report Id: fe2bf62d-be4e-4be3-aaf5-559981d6953a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by naveedmcp** [comment]
@jlattimer

**Comment by naveedmcp** [comment]
@jlattimer . Please update?

**Comment by sudmanche** [comment]
Same problem with web resource deployer.
