### ISSUE TITLE
Cannot connect using Office 365

### ISSUE THREAD

**Issue by zaha** [jlattimer/D365DeveloperExtensions#8]
Hi,

I just wanted to try out the beta and ran into the following issue when trying to connect via Office 365:

```
Source	: Microsoft.Xrm.Sdk
Method	: ThrowIfNull
Date	: 09.02.2018
Time	: 09:42:50
Error	: Value cannot be null.
Parameter name: identityProvider
Stack Trace	: at Microsoft.Xrm.Sdk.ClientExceptionHelper.ThrowIfNull(Object parameter, String name)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials, CrmLogEntry logSink)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.QueryLiveDiscoveryServer(ClientCredentials liveCreds, Uri discoServer)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.FindCrmOnlineDiscoveryServer(ClientCredentials liveCreds)
   at Microsoft.Xrm.Tooling.CrmConnectControl.CrmConnectionManager.ValidateServerConnection(CrmOrgByServer selectedOrg)
======================================================================================================================

```

Not sure what the problem is here. I tried all regions to eliminate the possibility of me choosing the wrong region. 

Cheers
Michael

**Comment by jlattimer** [comment]
If you get the latest version 9.x version of the Plug-in registration tool, does it connect? I do have a suspicion through that it won't since the login control I'm using should be the same one in as in the PRT.

**Comment by zaha** [comment]
Just tried it now and when I connect via the Plugin Registration Tool 9.0.0.7 it will open a new dialog to authenticate in. (Similar to all other applications we use with Okta) After that I saw a list of all available organizations and it worked.

I tried again directly after with VS 2017 and the Dev Extensions. This time, the following error occured when I tried the exact same steps as in the plugin registration tool:

```
Source	: Not Provided
Method	: Not Provided
Date	: 12.02.2018
Time	: 07:55:29
Error	: A CRM server name is required.
Parameter name: CrmServerName
Stack Trace	: Not Provided
======================================================================================================================

Source	: Not Provided
Method	: Not Provided
Date	: 12.02.2018
Time	: 07:55:32
Error	: A password is required.
Parameter name: CrmPassword
Stack Trace	: Not Provided
======================================================================================================================
```
My suspicion is that it does not show the popup it is supposed to where I can enter my user credentials for Okta.

**Comment by pawelgradecki** [comment]
I believe that you are using multi-factor authentication in your organization, that's why this is failing. @jlattimer have a look at this: https://stackoverflow.com/a/45241555/7708157maybe that's the case here. If someone has MFA, then this control from SDK won't connect correctly without this ClientId and RedirectId (I took the values from deassembled PluginRegistrationTool).

**Comment by jlattimer** [comment]
@zaha Can you try the latest beta release (2.0.1857.0510) and see if it solves your issue?

**Comment by jlattimer** [comment]
Thanks @pawelgradecki
